# Generated by Django 6.0.4 on 2026-04-17 09:39

import django.db.models.deletion
import horilla.registry.limiters
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_calendar', '0002_alter_useravailability_created_at_and_more'),
        ('horilla_core', '0013_alter_holiday_end_date_alter_holiday_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useravailability',
            name='google_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Google Calendar Event ID'),
        ),
        migrations.CreateModel(
            name='CustomCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Calendar Name')),
                ('color', models.CharField(default='#E74C3C', max_length=20, verbose_name='Color')),
                ('start_date_field', models.CharField(max_length=100, verbose_name='Start Date Field')),
                ('end_date_field', models.CharField(blank=True, max_length=100, verbose_name='End Date Field')),
                ('display_name_field', models.CharField(max_length=100, verbose_name='Display Name Field')),
                ('is_selected', models.BooleanField(default=True, verbose_name='Is Selected')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('module', models.ForeignKey(limit_choices_to=horilla.registry.limiters.ContentTypeLimiter('custom_calendar_models'), on_delete=django.db.models.deletion.CASCADE, to='horilla_core.horillacontenttype', verbose_name='Module')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_calendars', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Custom Calendar',
                'verbose_name_plural': 'Custom Calendars',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomCalendarCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field', models.CharField(max_length=100, verbose_name='Field Name')),
                ('operator', models.CharField(choices=[('exact', 'Equals'), ('ne', 'Not Equals'), ('icontains', 'Contains'), ('not_contains', 'Does Not Contain'), ('istartswith', 'Starts With'), ('iendswith', 'Ends With'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('isnull', 'Is Empty'), ('isnotnull', 'Is Not Empty'), ('between', 'Between')], max_length=50, verbose_name='Operator')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Sequence')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('custom_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='horilla_calendar.customcalendar', verbose_name='Custom Calendar')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Custom Calendar Condition',
                'verbose_name_plural': 'Custom Calendar Conditions',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('credentials_json', models.JSONField(blank=True, null=True, verbose_name='Credentials JSON')),
                ('redirect_uri', models.URLField(blank=True, null=True, verbose_name='Redirect URI')),
                ('google_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Connected Google Account')),
                ('token', models.JSONField(blank=True, default=dict, null=True, verbose_name='OAuth Token')),
                ('oauth_state', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='OAuth State')),
                ('sync_direction', models.CharField(choices=[('horilla_to_google', 'One-way: App → Google Calendar'), ('both', 'Two-way: App ↔ Google Calendar')], default='both', max_length=20, verbose_name='Sync Direction')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Synced At')),
                ('google_sync_token', models.CharField(blank=True, max_length=500, null=True, verbose_name='Google Sync Token')),
                ('watch_channel_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Watch Channel ID')),
                ('watch_resource_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Watch Resource ID')),
                ('watch_expiration', models.DateTimeField(blank=True, null=True, verbose_name='Watch Channel Expiration')),
                ('watch_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Watch Channel Token')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_config', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Google Calendar Configuration',
                'verbose_name_plural': 'Google Calendar Configurations',
            },
        ),
        migrations.CreateModel(
            name='GoogleIntegrationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_google_calendar_enabled', models.BooleanField(default=False, help_text='When enabled, users in this company can connect their Google Calendar.', verbose_name='Enable Google Calendar Integration')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Google Integration Setting',
                'verbose_name_plural': 'Google Integration Settings',
            },
        ),
    ]
