# Generated by Django 6.0.3 on 2026-03-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_dashboard', '0005_alter_dashboardcomponent_chart_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcomponent',
            name='y_axis_metric_type',
            field=models.CharField(blank=True, default='count', max_length=100, null=True, verbose_name='Y-axis Metric Type'),
        ),
        migrations.AlterField(
            model_name='componentcriteria',
            name='operator',
            field=models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('greater_than', 'Greater Than'), ('greater_than_equal', 'Greater Than or Equal'), ('less_than', 'Less Than'), ('less_than_equal', 'Less Than or Equal'), ('is_empty', 'Is Empty'), ('is_not_empty', 'Is Not Empty'), ('exact', 'Equals'), ('gt', 'After'), ('lt', 'Before'), ('between', 'Between'), ('isnull', 'Is empty'), ('isnotnull', 'Is not empty')], max_length=50, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='dashboardcomponent',
            name='metric_type',
            field=models.CharField(blank=True, default='count', max_length=100, null=True, verbose_name='Metric Type'),
        ),
    ]
