# Generated by Django 6.0.4 on 2026-04-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_activity', '0005_alter_activity_content_type_alter_activity_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='google_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Google Calendar Event ID'),
        ),
    ]
