# Generated by Django 6.0.4 on 2026-04-17 09:39

import django.db.models.deletion
import horilla.registry.limiters
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horilla_core', '0013_alter_holiday_end_date_alter_holiday_start_date'),
        ('horilla_mail', '0006_alter_horillamail_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('module', models.ForeignKey(help_text='Target module', limit_choices_to=horilla.registry.limiters.ContentTypeLimiter('cadence_models'), on_delete=django.db.models.deletion.PROTECT, to='horilla_core.horillacontenttype', verbose_name='Module')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Cadence',
                'verbose_name_plural': 'Cadences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CadenceCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field', models.CharField(max_length=100, verbose_name='Field Name')),
                ('operator', models.CharField(choices=[('exact', 'Equals'), ('ne', 'Not Equals'), ('icontains', 'Contains'), ('not_contains', 'Does Not Contain'), ('istartswith', 'Starts With'), ('iendswith', 'Ends With'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('isnull', 'Is Empty'), ('isnotnull', 'Is Not Empty'), ('between', 'Between')], max_length=50, verbose_name='Operator')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('logical_operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=3, verbose_name='Logical Operator')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('cadence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='horilla_cadences.cadence', verbose_name='Cadence')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Cadence Condition',
                'verbose_name_plural': 'Cadence Conditions',
            },
        ),
        migrations.CreateModel(
            name='CadenceFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('followup_number', models.PositiveSmallIntegerField(default=1, help_text='Stage number (1 = first follow-up).', verbose_name='Follow up')),
                ('followup_type', models.CharField(choices=[('task', 'Task'), ('call', 'Call'), ('email', 'Email')], max_length=20, verbose_name='Follow up Type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('do_this_unit', models.CharField(choices=[('immediately', 'Immediately'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('month', 'Month')], default='immediately', max_length=20, verbose_name='Do This')),
                ('do_this_value', models.PositiveIntegerField(blank=True, help_text='Required for minute/hour/day/month.', null=True, verbose_name='Do This Value')),
                ('previous_status', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('waiting', 'Waiting on Someone'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deferred', 'Deferred'), ('overdue', 'Overdue')], help_text='Required from follow up 2 onwards.', max_length=30, null=True, verbose_name='After Previous Status Is')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('due_after_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Trigger Date + Days')),
                ('task_status', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('waiting', 'Waiting on Someone'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deferred', 'Deferred')], max_length=20, null=True, verbose_name='Status')),
                ('task_priority', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True, verbose_name='Priority')),
                ('call_type', models.CharField(default='outbound', max_length=20, verbose_name='Call Type')),
                ('call_status', models.CharField(default='scheduled', max_length=20, verbose_name='Call Status')),
                ('call_start_after_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Call Start + Days')),
                ('purpose', models.CharField(blank=True, max_length=255, null=True, verbose_name='Purpose')),
                ('to', models.TextField(blank=True, help_text='Recipients for this step. Choose user/email fields from the record', null=True, verbose_name='Mail to')),
                ('branch_from', models.ForeignKey(blank=True, help_text='Set when this step was created from a specific parent card’s + (next stage).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_children', to='horilla_cadences.cadencefollowup', verbose_name='Branched from')),
                ('cadence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='horilla_cadences.cadence', verbose_name='Cadence')),
                ('call_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadence_call_followups', to=settings.AUTH_USER_MODEL, verbose_name='Call Owner')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadence_followups', to='horilla_mail.horillamailtemplate', verbose_name='Mail Template')),
                ('task_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadence_task_followups', to=settings.AUTH_USER_MODEL, verbose_name='Task Owner')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Cadence Follow up',
                'verbose_name_plural': 'Cadence Follow ups',
                'ordering': ['followup_number', 'order', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('followup_number', 1)), fields=('cadence',), name='unique_first_followup_per_cadence'), models.UniqueConstraint(condition=models.Q(('followup_number__gt', 1), ('previous_status__isnull', False), ('branch_from__isnull', True)), fields=('cadence', 'followup_number', 'previous_status'), name='unique_previous_status_per_followup_bucket_unbranched'), models.UniqueConstraint(condition=models.Q(('followup_number__gt', 1), ('previous_status__isnull', False), ('branch_from__isnull', False)), fields=('cadence', 'followup_number', 'branch_from', 'previous_status'), name='unique_previous_status_per_followup_bucket_branch')],
            },
        ),
    ]
